"""add prompt metadata

Revision ID: f7ec68566feb
Revises: 
Create Date: 2026-09-19 14:42:08.115684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7ec68566feb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('is_pinned', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('prompts', sa.Column('last_opened_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompts', 'last_opened_at')
    op.drop_column('prompts', 'is_pinned')
    # ### end Alembic commands ###
